/*M!999999\- enable the sandbox mode */ 
-- MariaDB dump 10.19  Distrib 10.11.14-MariaDB, for debian-linux-gnu (x86_64)
--
-- Host: localhost    Database: sgw
-- ------------------------------------------------------
-- Server version	10.11.14-MariaDB-0ubuntu0.24.04.1

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `unit_catalog`
--

DROP TABLE IF EXISTS `unit_catalog`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `unit_catalog` (
  `unit_id` int(11) NOT NULL AUTO_INCREMENT,
  `unit_code` varchar(12) NOT NULL,
  `category` enum('military','civilian','government') NOT NULL,
  `class_letter` varchar(4) NOT NULL DEFAULT 'A',
  `class_subclass` varchar(4) NOT NULL DEFAULT 'I',
  `unit_type` varchar(32) NOT NULL DEFAULT 'Infantry',
  `unit_subtype` varchar(40) NOT NULL DEFAULT 'Standard',
  `tier` int(11) NOT NULL DEFAULT 1,
  `rank_level` int(11) NOT NULL DEFAULT 1,
  `rank_abbrev` varchar(16) NOT NULL DEFAULT 'Pvt',
  `rank_title` varchar(64) NOT NULL DEFAULT 'Private',
  `unit_name` varchar(80) NOT NULL DEFAULT 'Infantry Unit',
  `full_title` varchar(120) NOT NULL DEFAULT '',
  `training_cost` int(11) NOT NULL DEFAULT 500,
  `upkeep_per_turn` int(11) NOT NULL DEFAULT 10,
  `attack_power` int(11) NOT NULL DEFAULT 0,
  `defense_power` int(11) NOT NULL DEFAULT 0,
  `covert_power` int(11) NOT NULL DEFAULT 0,
  `income_gen` int(11) NOT NULL DEFAULT 0,
  `special_ability` varchar(160) NOT NULL DEFAULT '',
  `description` text DEFAULT NULL,
  PRIMARY KEY (`unit_id`),
  UNIQUE KEY `unit_code` (`unit_code`),
  KEY `idx_cat_tier` (`category`,`tier`)
) ENGINE=InnoDB AUTO_INCREMENT=91 DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `unit_catalog`
--

LOCK TABLES `unit_catalog` WRITE;
/*!40000 ALTER TABLE `unit_catalog` DISABLE KEYS */;
INSERT INTO `unit_catalog` VALUES
(1,'MIL-001','military','A','I','Infantry','Frontline Conscript',1,1,'Pvt','Private','Infantry Conscript','Tier 1 – Private | Class A-I Frontline Conscript',500,5,4,2,0,0,'Cannon Fodder: losses count half toward moral penalty','The lowest rank in active service. Conscripts are issued standard-issue arms and assigned to forward positions to absorb enemy fire and probe defensive lines.'),
(2,'MIL-002','military','A','II','Infantry','Marksman',1,2,'PFC','Private First Class','Marksman','Tier 1 – PFC | Class A-II Marksman',650,6,6,3,0,0,'Precision Strike: +5% chance of critical hit','Assigned a scoped rifle after demonstrating above-average aim scores. Marksmen operate at the edge of engagement range and soften enemy concentrations before full assault.'),
(3,'MIL-003','military','A','III','Infantry','Combat Engineer',1,3,'Spc','Specialist','Combat Engineer','Tier 1 – Specialist | Class A-III Combat Engineer',800,7,5,6,0,0,'Field Fortify: +2 defense when building barricades','Specialists blend combat skills with technical knowledge. They breach fortifications, lay mines, repair vehicles under fire, and establish defensive perimeters in contested zones.'),
(4,'MIL-004','military','B','I','Infantry','Squad Leader',2,4,'Cpl','Corporal','Squad Leader','Tier 2 – Corporal | Class B-I Squad Leader',1200,10,8,8,1,0,'Rally: adjacent units gain +1 attack this turn','Corporals lead four-man fire teams and are the first rung of the NCO ladder. They enforce discipline, report field conditions up the chain, and lead small-unit actions autonomously.'),
(5,'MIL-005','military','B','II','Infantry','Fire Team Lead',2,5,'Sgt','Sergeant','Sergeant of Arms','Tier 2 – Sergeant | Class B-II Fire Team Lead',1600,12,12,10,1,0,'Suppressive Fire: enemy attack -10% for one turn','The backbone of the enlisted corps. Sergeants coordinate small-unit tactics, manage squad equipment and morale, and execute platoon-level orders with precision.'),
(6,'MIL-006','military','B','III','Infantry','Platoon Sergeant',2,6,'SSgt','Staff Sergeant','Platoon Sergeant','Tier 2 – Staff Sergeant | Class B-III Platoon Sergeant',2000,14,14,14,2,0,'Iron Discipline: reduces desertion rate by 5%','Staff Sergeants manage platoon operations and act as the primary link between officers and enlisted soldiers. Their experience in sustained operations makes them invaluable in long campaigns.'),
(7,'MIL-007','military','C','I','Infantry','Combat Advisor',3,7,'SFC','Sergeant First Class','Combat Advisor','Tier 3 – SFC | Class C-I Combat Advisor',3000,18,18,16,3,0,'Tactical Overlay: reveals enemy unit composition in a zone','Assigned to advise company-level commanders, SFCs bring deep operational knowledge and are often embedded with allied or newly trained forces to improve their battlefield effectiveness.'),
(8,'MIL-008','military','C','II','Heavy Weapons','Weapons Master',3,8,'MSG','Master Sergeant','Weapons Master','Tier 3 – Master Sergeant | Class C-II Weapons Master',4000,20,22,18,2,0,'Heavy Caliber: +15% attack when equipped with heavy weapons','Master Sergeants are seasoned veterans trusted with the heaviest weapons in the platoon. They train units in advanced weapons doctrine and lead heavy-assault element operations.'),
(9,'MIL-009','military','C','III','Infantry','Regimental Sergeant',3,9,'SGM','Sergeant Major','Regimental Sergeant Major','Tier 3 – SGM | Class C-III Regimental Sergeant Major',5000,22,20,22,4,0,'Unit Cohesion: friendly units take 5% less casualties','The senior enlisted advisor to a regimental commander. Sergeant Majors represent the collective experience of thousands of field operations and enforce standards that define battle-ready forces.'),
(10,'MIL-010','military','D','I','Officer','Platoon Commander',4,10,'2LT','Second Lieutenant','Platoon Commander','Tier 4 – 2LT | Class D-I Platoon Commander',7000,28,24,20,5,0,'Advance Order: units move before enemy in opening turn','Fresh from officer training, Second Lieutenants lead 30-50 soldiers into combat. They translate strategic orders into tactical movement and are known for aggressive execution.'),
(11,'MIL-011','military','D','II','Officer','Company XO',4,11,'1LT','First Lieutenant','Company Executive Officer','Tier 4 – 1LT | Class D-II Company XO',9000,32,28,26,6,0,'Logistics Mastery: reduces supply consumption by 8%','First Lieutenants act as the second-in-command for a company and manage supply lines, personnel actions, and training programs while serving as a ready replacement for the Company Commander.'),
(12,'MIL-012','military','D','III','Officer','Company Commander',4,12,'CPT','Captain','Captain of the Line','Tier 4 – Captain | Class D-III Company Commander',12000,36,34,30,7,0,'Command Presence: morale bonus to all friendly units in sector','Captains command 100-200 soldiers across multiple platoons. They are the primary fighting leaders of the army, capable of independent tactical operations and sustained combat management.'),
(13,'MIL-013','military','E','I','Officer','Battalion Operations',5,13,'MAJ','Major','Operations Major','Tier 5 – Major | Class E-I Battalion Operations Officer',18000,45,40,36,9,0,'Operational Planning: +10% attack on planned engagements','Majors fill staff roles at battalion level, managing operations, intelligence, and logistics cycles. They are the invisible engine of effective battalion-level warfare.'),
(14,'MIL-014','military','E','II','Officer','Battalion Commander',5,14,'LTC','Lieutenant Colonel','Battalion Commander','Tier 5 – LTC | Class E-II Battalion Commander',25000,55,50,44,10,0,'Coordinated Assault: unlocks multi-unit synchronized attack','Lieutenant Colonels command 300-900 soldiers. They lead combined arms teams of infantry, armor, and fire support and are authorized to conduct independent campaign-level operations.'),
(15,'MIL-015','military','E','III','Officer','Brigade Commander',5,15,'COL','Colonel','Brigade Commander','Tier 5 – Colonel | Class E-III Brigade Commander',35000,65,62,54,11,0,'Strategic Reserve: may redeploy 20% of forces between engagements','Colonels command brigades of 3,000-5,000 soldiers and serve as the senior tactical leaders of the ground force. They bridge operational planning and direct combat execution.'),
(16,'MIL-016','military','F','I','General Officer','Division Asst Commander',6,16,'BG','Brigadier General','Brigadier General','Tier 6 – BG | Class F-I Division Assistant Commander',55000,80,75,65,14,0,'Flanking Doctrine: +20% attack when striking enemy rear','One-star generals are the first step into the senior leadership tier. They command small division elements and serve as the primary deputies to Major Generals in division-level campaigns.'),
(17,'MIL-017','military','F','II','General Officer','Division Commander',6,17,'MG','Major General','Division Commander','Tier 6 – MG | Class F-II Division Commander',80000,95,90,78,16,0,'Combined Arms: unlocks joint infantry-fleet attack option','Major Generals command 10,000-20,000 soldiers in divisional formations. They are responsible for multi-domain operations and coordinate with fleet and orbital assets for planet-wide campaigns.'),
(18,'MIL-018','military','F','III','General Officer','Corps Commander',6,18,'LTG','Lieutenant General','Corps Commander','Tier 6 – LTG | Class F-III Corps Commander',120000,110,108,95,18,0,'Theatre Dominance: enemy morale -15% in controlled sectors','Three-star generals lead corps of 20,000-45,000 troops across multi-division fronts. They direct campaign-level operations and integrate political, diplomatic, and military objectives.'),
(19,'MIL-019','military','G','I','Special Forces','Black Ops Agent',7,19,'W1','Warrant Officer','Shadow Operative','Tier 7 – W1 | Class G-I Shadow Operative',180000,130,60,40,120,0,'Ghost Protocol: invisible to enemy scouts for 1 turn','Shadow Operatives undergo years of psychological and physical conditioning beyond standard military training. They operate in denied areas, execute covert raids, and eliminate high-value targets without leaving a trace.'),
(20,'MIL-020','military','G','II','Special Forces','Wraith Hunter',7,20,'W2','Chief Warrant Officer','Wraith Hunter','Tier 7 – W2 | Class G-II Wraith Hunter',250000,150,80,55,140,0,'Anti-Extraterrestrial Training: +30% attack vs alien races','Wraith Hunters are trained specifically to track and neutralize Wraith warriors, replicators, and other extraterrestrial threats. Their specialized combat doctrine makes them devastating in asymmetric engagements against non-human forces.'),
(21,'MIL-021','military','G','III','Special Forces','Ancient Guardian',7,21,'W3','Master Warrant Officer','Ancient Guardian','Tier 7 – W3 | Class G-III Ancient Guardian',350000,170,100,90,160,0,'Ancient Armor Protocol: damage reduction 15% from all sources','Ancient Guardians are bonded to Ancient defensive technology and serve as elite sentinels for critical facilities, stargates, and planetary command nodes. Their combat endurance far exceeds standard special forces.'),
(22,'MIL-022','military','H','I','Super Soldier','Phase Commando',8,22,'E-SS1','Super Soldier Grade 1','Ascended Warrior','Tier 8 – SS1 | Class H-I Phase Commando',600000,200,180,120,80,0,'Phase Shift: may avoid one attack per engagement cycle','Ascended Warriors have undergone partial ascension, granting them heightened perception, accelerated regeneration, and the ability to briefly shift between physical and energy states during combat.'),
(23,'MIL-023','military','H','II','Super Soldier','Subspace Commando',8,23,'E-SS2','Super Soldier Grade 2','Quantum Striker','Tier 8 – SS2 | Class H-II Subspace Commando',900000,230,220,140,100,0,'Quantum Blink: teleports behind enemy lines for a flanking attack','Quantum Strikers operate using prototype subspace displacement units, allowing them to instantaneously relocate to pre-calculated coordinates. They strike enemy command elements and weapon caches before defensive forces can respond.'),
(24,'MIL-024','military','H','III','Super Soldier','Dark Matter Infantryman',8,24,'E-SS3','Super Soldier Grade 3','Void Walker','Tier 8 – SS3 | Class H-III Dark Matter Infantryman',1300000,260,260,180,120,0,'Dark Matter Armor: immune to energy-based damage for 1 turn','Void Walkers are encased in experimental dark matter containment suits. They absorb, redirect, and reflect energy weaponry, making conventional beam and plasma attacks nearly ineffective against them in short engagements.'),
(25,'MIL-025','military','I','I','High Command','Army Commander',9,25,'GEN','General','Four-Star General','Tier 9 – General | Class I-I Army Commander',2000000,320,300,260,40,0,'Total War Doctrine: all unit costs reduced 10% for 24 hours','Four-star generals command entire planetary armies and direct multi-front operations. They interface directly with political leadership and possess authority to authorize strategic weapons use.'),
(26,'MIL-026','military','I','II','High Command','Theatre Commander',9,26,'MAR','Marshal','Grand Marshal','Tier 9 – Marshal | Class I-II Theatre Commander',3500000,380,360,310,50,0,'Theatre Wide Strike: simultaneous attack on all enemy positions','Grand Marshals command entire theatres of war spanning multiple planets and star systems. They coordinate land, sea, air, and orbital forces with a precision that defines the outcome of galactic conflicts.'),
(27,'MIL-027','military','I','III','High Command','Supreme War Commander',9,27,'SC','Supreme Commander','Supreme Commander of All Forces','Tier 9 – Supreme Commander | Class I-III Supreme War Commander',6000000,450,440,380,60,0,'Supreme Directive: override enemy defensive formations for 1 engagement','The Supreme Commander holds absolute authority over all military forces in an empire. Their orders take precedence over planetary governors and only the Head of State can countermand their strategic directives.'),
(28,'MIL-028','military','J','I','Legendary','Eternal Warrior',10,28,'DK','Death Knight','Death Knight Commander','Tier 10 – Death Knight | Class J-I Eternal Warrior',10000000,600,600,500,80,0,'Soul Harvest: each kill restores 2% of max health to wielder','Death Knights are warriors who have returned from beyond death through Ancient or Ori technology. Their combat capability is without equal among mortal soldiers and they feel no fear, no fatigue, and no mercy.'),
(29,'MIL-029','military','J','II','Legendary','Chrono Combat Agent',10,29,'TS','Time Soldier','Chrono Soldier Prime','Tier 10 – Time Soldier | Class J-II Chrono Combat Agent',18000000,700,680,560,100,0,'Temporal Displacement: rewind combat result once per battle','Time Soldiers are equipped with unstable but functional chronal displacement devices recovered from Reetou ruins. They can rewind a failed engagement or pre-empt an ambush by acting on knowledge of events seconds before they occur.'),
(30,'MIL-030','military','J','III','Legendary','Ascended Champion',10,30,'EW','Eternity Warden','Eternity Warden Supreme','Tier 10 – Eternity Warden | Class J-III Ascended Champion',30000000,900,900,800,200,0,'Eternal Guard: cannot be killed; retreats instead of dying','The Eternity Warden exists partially outside physical reality. They have fully integrated Ancient ascension technology into their being, giving them capabilities that blur the line between soldier and deity. They are effectively unkillable — when overwhelmed, they simply step through reality to fight another day.'),
(31,'CIV-001','civilian','A','I','Agriculture','Field Laborer',1,1,'FL','Farmer','Subsistence Farmer','Tier 1 – Farmer | Class A-I Agricultural Laborer',200,3,0,0,0,80,'Harvest Bonus: +5% food production on owned planets','The base of any civilization. Farmers cultivate food crops across colonized worlds and provide the essential nutritional foundation for population growth and military sustainment.'),
(32,'CIV-002','civilian','A','II','Mining','Ore Extractor',1,2,'MN','Miner','Raw Ore Miner','Tier 1 – Miner | Class A-II Ore Extractor',300,4,0,0,0,120,'Deep Vein: +8% metal deposit extraction rate','Miners extract raw ore from planetary deposits, feeding the smelters and fabricators that produce metals for construction, shipbuilding, and weapons manufacturing.'),
(33,'CIV-003','civilian','A','III','Labor','General Worker',1,3,'LB','Laborer','General Laborer','Tier 1 – Laborer | Class A-III General Worker',150,2,0,0,0,60,'Flexible Labor: can be assigned to any production task','General Laborers perform unspecialized physical work across all sectors of the economy. They are the most numerous of all civilian unit types and the backbone of rapid colonization efforts.'),
(34,'CIV-004','civilian','B','I','Skilled Trades','Artisan',2,4,'CR','Craftsman','Master Craftsman','Tier 2 – Craftsman | Class B-I Artisan',500,6,0,1,0,200,'Crafted Goods: +10% income from trade routes','Craftsmen produce refined goods from raw materials — pottery, textiles, tools, and luxury items. Their output drives trade economy and improves quality of life metrics that affect population growth rates.'),
(35,'CIV-005','civilian','B','II','Skilled Trades','Metal Worker',2,5,'BS','Blacksmith','Master Blacksmith','Tier 2 – Blacksmith | Class B-II Metal Worker',700,7,0,2,0,260,'Weapon Smithing: reduces military equipment repair cost 5%','Blacksmiths forge metals into tools, components, and basic weapons. They occupy a critical role bridging raw material extraction and finished goods production, especially for military supply chains.'),
(36,'CIV-006','civilian','B','III','Construction','Site Specialist',2,6,'MS','Mason','Master Mason','Tier 2 – Mason | Class B-III Construction Specialist',900,8,0,3,0,300,'Structural Integrity: buildings have +5% durability','Masons plan and execute stone and composite construction. On colony worlds, their skills translate directly into faster base-building timelines and stronger defensive fortifications.'),
(37,'CIV-007','civilian','C','I','Technical','Equipment Technician',3,7,'MCH','Mechanic','Systems Mechanic','Tier 3 – Mechanic | Class C-I Equipment Technician',1500,11,0,2,2,450,'Field Repair: fleet repair time reduced 10%','Mechanics maintain the machinery of civilization. From ground vehicles to orbital docking clamps, their work keeps fleets operational and colony infrastructure running between scheduled overhauls.'),
(38,'CIV-008','civilian','C','II','Technical','Junior Engineer',3,8,'ENG1','Engineer I','Junior Systems Engineer','Tier 3 – Engineer I | Class C-II Junior Engineer',2200,14,0,3,2,580,'Blueprint Analysis: +5% build speed on all construction','Junior Engineers apply scientific principles to system design. They assist senior engineers with calculations, draft initial construction plans, and supervise technical crews on colony build-out projects.'),
(39,'CIV-009','civilian','C','III','Technical','Land Specialist',3,9,'SUR','Surveyor','Planetary Surveyor','Tier 3 – Surveyor | Class C-III Land Specialist',2000,12,0,2,4,520,'Resource Survey: reveals hidden resource veins on owned planets','Surveyors map terrain, subsoil composition, and atmospheric conditions on newly colonized planets. Their assessments directly determine optimal placement for mines, farms, and defensive installations.'),
(40,'CIV-010','civilian','D','I','Professional','Medical Officer',4,10,'DR','Doctor','Chief Medical Officer','Tier 4 – Doctor | Class D-I Medical Officer',4000,18,0,2,0,800,'Field Triage: reduces friendly casualties by 5% post-battle','Doctors maintain the health and combat readiness of the civilian and military population. In war zones they operate field hospitals, perform emergency surgery, and prevent epidemic outbreaks from compromising campaign objectives.'),
(41,'CIV-011','civilian','D','II','Professional','Legal Counsel',4,11,'LAW','Lawyer','Imperial Legal Counsel','Tier 4 – Lawyer | Class D-II Legal Counsel',4500,19,0,0,6,900,'Treaty Leverage: diplomatic agreements last 20% longer','Imperial Lawyers draft, negotiate, and enforce legal frameworks across planetary jurisdictions. Their expertise in interstellar law enables favorable treaty terms and protects empire assets from rival claim challenges.'),
(42,'CIV-012','civilian','D','III','Professional','Education Officer',4,12,'TCH','Teacher','Senior Education Officer','Tier 4 – Teacher | Class D-III Education Officer',3500,16,0,0,0,750,'Knowledge Transfer: technology research speed +6%','Teachers and instructors accelerate the education of new colonists, training future engineers, medics, and specialists. Their presence directly improves long-term productivity of the workforce.'),
(43,'CIV-013','civilian','E','I','Engineering','Systems Engineer',5,13,'ENG3','Engineer III','Senior Systems Engineer','Tier 5 – Engineer III | Class E-I Systems Engineer',8000,28,0,5,3,1500,'System Optimization: all production structures +8% output','Senior Engineers design and maintain the core technical systems of civilization. Their specialization in propulsion, energy, or environmental control means a single engineer can dramatically improve the efficiency of an entire colony.'),
(44,'CIV-014','civilian','E','II','Science','Research Analyst',5,14,'SCI','Scientist','Imperial Research Scientist','Tier 5 – Scientist | Class E-II Research Analyst',10000,32,0,2,5,1800,'Breakthrough Protocol: +10% chance of technology discovery each turn','Scientists conduct theoretical and applied research that underpins technological advancement. Their discoveries feed directly into the technology tree and can unlock previously inaccessible upgrade branches.'),
(45,'CIV-015','civilian','E','III','Architecture','Urban Designer',5,15,'ARC','Architect','Urban Architect','Tier 5 – Architect | Class E-III Urban Designer',9000,30,0,4,0,1650,'Urban Grid: colony housing capacity +12%','Architects design the built environment at scale — from individual colony habitats to planetary city grids. Their master plans determine how efficiently populations are housed, how quickly colonies scale, and how defensible civilian zones are during attack.'),
(46,'CIV-016','civilian','F','I','Engineering','Chief Technical Officer',6,16,'MENG','Master Engineer','Master Engineer Prime','Tier 6 – Master Engineer | Class F-I Chief Technical Officer',18000,45,0,8,5,3000,'Grand Design: building upgrade costs reduced 15%','Master Engineers occupy the highest technical leadership role below the executive tier. They oversee entire engineering divisions, approve final technical specifications, and personally solve the most complex infrastructure challenges.'),
(47,'CIV-017','civilian','F','II','Science','Principal Researcher',6,17,'LSCI','Lead Scientist','Lead Scientist Principal','Tier 6 – Lead Scientist | Class F-II Principal Researcher',22000,50,0,3,8,3600,'Accelerated Discovery: technology points gained +15% per turn','Lead Scientists direct multi-disciplinary research teams toward civilization-defining breakthroughs. Their integration of Ancient, Asgard, and human science disciplines allows for synthesis discoveries that no single tradition could produce alone.'),
(48,'CIV-018','civilian','F','III','Architecture','City Planning Director',6,18,'CARC','Chief Architect','Chief Architect of the Empire','Tier 6 – Chief Architect | Class F-III City Planning Director',20000,48,0,6,0,3200,'Imperial Scale: new colony build slots +2','Chief Architects design at imperial scale — entire planetary city systems, orbital platform layouts, and hyperspace infrastructure corridors. Their plans shape the physical reality of expansion.'),
(49,'CIV-019','civilian','G','I','Specialist','Gate Technician',7,19,'SGATE','Stargate Operator','Stargate Operations Specialist','Tier 7 – Stargate Operator | Class G-I Gate Technician',40000,65,0,2,15,5000,'Gate Efficiency: hyperspace transit costs reduced 20%','Stargate Operators are certified in both Ancient gate technology and modern dialing protocols. They manage gate address libraries, configure wormhole stability parameters, and oversee all transit operations in a sector.'),
(50,'CIV-020','civilian','G','II','Specialist','Energy Specialist',7,20,'NTECH','Naquadah Technician','Naquadah Energy Specialist','Tier 7 – Naquadah Tech | Class G-II Energy Specialist',55000,75,0,3,10,6500,'Naquadah Surge: energy reactor output +25% for 4 hours','Naquadah Technicians are trained in the extraction, refinement, and safe handling of naquadah and its enhanced isotopes. Their expertise enables safe deployment of naquadah-enhanced reactors and weapons systems.'),
(51,'CIV-021','civilian','G','III','Specialist','Relic Researcher',7,21,'ANSCH','Ancient Scholar','Ancient Relic Scholar','Tier 7 – Ancient Scholar | Class G-III Relic Researcher',70000,80,0,4,18,7500,'Ancient Insight: unlocks one additional technology per ascension tier','Ancient Scholars study the written, material, and energy records left by the Ancients across the galaxy. Their translations of Ancient databases have unlocked entire branches of technology otherwise inaccessible to modern civilizations.'),
(52,'CIV-022','civilian','H','I','Executive','Settlement Administrator',8,22,'CDIR','Colony Director','Imperial Colony Director','Tier 8 – Colony Director | Class H-I Settlement Administrator',120000,100,0,6,12,12000,'Colony Acceleration: new colonies reach stable status 2 turns faster','Colony Directors oversee the complete lifecycle of planetary settlements from initial touchdown through full self-sufficiency. Their administrative expertise determines the survival rate of frontier colonies in hostile environments.'),
(53,'CIV-023','civilian','H','II','Executive','Trade Executive',8,23,'ECON','Economic Minister','Imperial Economic Minister','Tier 8 – Economic Minister | Class H-II Trade Executive',160000,115,0,3,15,16000,'Market Mastery: market listing fees reduced to 2%','Economic Ministers manage the financial systems of entire planetary economies. They set trade tariffs, negotiate resource exchange agreements, and develop the banking infrastructure that funds continuous military expansion.'),
(54,'CIV-024','civilian','H','III','Executive','Production Chief',8,24,'IGOV','Industrial Governor','Imperial Industrial Governor','Tier 8 – Industrial Governor | Class H-III Production Chief',180000,120,0,8,10,18000,'Industrial Surge: all resource production +12% for 2 turns','Industrial Governors direct the extraction and manufacturing sectors of a planetary economy. They optimize supply chains, commission new mining operations, and ensure production quotas are met even during wartime disruptions.'),
(55,'CIV-025','civilian','I','I','Master','Imperial Engineer',9,25,'GENG','Grand Engineer','Grand Imperial Engineer','Tier 9 – Grand Engineer | Class I-I Imperial Engineer',400000,180,0,12,8,32000,'Engineering Mastery: all buildings gain 1 bonus level permanently','Grand Engineers are the supreme technical authority in an empire. They have personally designed and built megastructures — orbital rings, planetary shield generators, and gate networks — that define the defensive and economic profile of civilizations.'),
(56,'CIV-026','civilian','I','II','Master','Imperial Researcher',9,26,'GSCI','Grand Scientist','Grand Imperial Scientist','Tier 9 – Grand Scientist | Class I-II Imperial Researcher',550000,200,0,5,20,40000,'Scientific Supremacy: all technology costs reduced 20%','Grand Scientists represent the pinnacle of research achievement. They synthesize knowledge from Ancient, Asgard, Tok\'ra, and human sources to produce unified theories that advance entire branches of the technology tree simultaneously.'),
(57,'CIV-027','civilian','I','III','Master','Imperial Designer',9,27,'GARC','Grand Architect','Grand Imperial Architect','Tier 9 – Grand Architect | Class I-III Imperial Designer',480000,190,0,10,8,36000,'Imperial Blueprint: colony maximum build slots increased by 4','Grand Architects redesign the physical form of empires. They plan and execute the construction of orbital stations, planetary megacities, and stargate hub networks that sustain civilizations at galactic scale.'),
(58,'CIV-028','civilian','J','I','Legendary','Ancient Knowledge Bearer',10,28,'ASCH','Ascended Scholar','Ascended Scholar Eternal','Tier 10 – Ascended Scholar | Class J-I Ancient Knowledge Bearer',1200000,280,0,8,40,80000,'Living Library: all technology research requirements halved','Ascended Scholars have transcended physical limitations and carry the accumulated knowledge of the Ancients directly in their consciousness. Their presence in an empire effectively fast-forwards its technological development by centuries.'),
(59,'CIV-029','civilian','J','II','Legendary','Chrono Trade Master',10,29,'TECO','Time Economist','Chrono Trade Master Eternal','Tier 10 – Time Economist | Class J-II Chrono Trade Master',2000000,320,0,4,30,120000,'Market Omniscience: always sells at peak price, buys at minimum','Time Economists have been exposed to subspace economic data streams that show market price trajectories across multiple timeline branches. They cannot lose a trade, ever, and their guidance generates extraordinary wealth for any empire they serve.'),
(60,'CIV-030','civilian','J','III','Legendary','Reality Architect',10,30,'VBLD','Void Builder','Void Builder Supreme','Tier 10 – Void Builder | Class J-III Reality Architect',3500000,400,0,15,20,200000,'Reality Construction: can build any structure instantly once per 48 hours','Void Builders operate at the intersection of physical engineering and subspace physics. They can phase-construct megastructures by folding subspace material into real-space in minutes rather than years.'),
(61,'GOV-001','government','A','I','Administration','Municipal Clerk',1,1,'CLK','Ward Clerk','Municipal Record Keeper','Tier 1 – Ward Clerk | Class A-I Municipal Clerk',300,4,0,1,2,100,'Registration Efficiency: colonist onboarding +5% faster','Ward Clerks manage the baseline administrative functions of a colony — registering citizens, recording property deeds, processing permits, and maintaining census data that underpins all higher governance functions.'),
(62,'GOV-002','government','A','II','Administration','District Liaison',1,2,'WO','Ward Officer','District Ward Officer','Tier 1 – Ward Officer | Class A-II District Liaison',500,5,0,2,3,150,'Public Order: minor unrest events resolved automatically','Ward Officers patrol administrative districts and serve as the face of government authority at the street level. They process complaints, maintain public order, and serve as the primary conduit between citizens and higher government.'),
(63,'GOV-003','government','A','III','Revenue','Revenue Agent',1,3,'TC','Tax Collector','Imperial Revenue Agent','Tier 1 – Tax Collector | Class A-III Revenue Agent',600,6,0,1,5,220,'Efficient Collection: tax income +8%','Tax Collectors enforce revenue obligations across colonial populations. Their work funds everything from municipal services to interstellar military campaigns, and their efficiency directly determines the speed of economic expansion.'),
(64,'GOV-004','government','B','I','Judiciary','Local Justice',2,4,'MAG','City Magistrate','Municipal Magistrate','Tier 2 – Magistrate | Class B-I Local Justice',1200,9,0,3,5,400,'Legal Order: enemy espionage detected 5% more often','Magistrates preside over municipal courts, adjudicating civil disputes, criminal cases, and regulatory violations. Their rulings set legal precedent that governs citizen behavior and corporate conduct within their jurisdiction.'),
(65,'GOV-005','government','B','II','Legislature','Municipal Representative',2,5,'CC','City Councilor','City Council Representative','Tier 2 – City Councilor | Class B-II Municipal Representative',1500,10,0,2,4,500,'Coalition Building: +5% ally income bonus while in alliance','City Councilors represent local interests in the municipal legislative body. They vote on city budgets, zoning laws, and emergency measures. Skilled councilors build coalitions that amplify local political power up the governance chain.'),
(66,'GOV-006','government','B','III','Executive','City Executive',2,6,'MYR','Mayor','Mayor of the City','Tier 2 – Mayor | Class B-III City Executive',2500,14,0,5,6,750,'Urban Development: city income +12%','Mayors govern entire city-states and are the primary executive authority for populations of tens of thousands. They direct emergency services, negotiate with corporations and planetary government, and serve as the public face of local administration.'),
(67,'GOV-007','government','C','I','Administration','Regional Administrator',3,7,'DPF','District Prefect','District Prefect Commander','Tier 3 – District Prefect | Class C-I Regional Administrator',4000,18,0,6,8,1200,'Administrative Control: reduces colony unrest by 10%','District Prefects manage regional administration across multiple cities and settlements. They coordinate emergency response, enforce planetary law, and serve as the senior representative of central government authority in outlying zones.'),
(68,'GOV-008','government','C','II','Executive','Province Leader',3,8,'RGOV','Regional Governor','Provincial Governor','Tier 3 – Regional Governor | Class C-II Province Leader',6000,22,0,8,10,1800,'Provincial Authority: provincial resource output +10%','Provincial Governors command full provinces of millions of inhabitants. They hold executive, legislative, and judicial authority within their territory and report directly to the planetary head of government.'),
(69,'GOV-009','government','C','III','Judiciary','Regional Judiciary',3,9,'CJG','Circuit Judge','Imperial Circuit Judge','Tier 3 – Circuit Judge | Class C-III Regional Judiciary',5000,20,0,5,12,1500,'Judicial Reach: espionage penalties on empire reduced 8%','Circuit Judges travel between planetary courts dispensing imperial law across vast territorial circuits. Their rulings have the weight of the imperial judiciary and can reverse decisions made by lower courts.'),
(70,'GOV-010','government','D','I','Administration','Territorial Manager',4,10,'PADM','Province Administrator','Imperial Province Administrator','Tier 4 – Province Admin | Class D-I Territorial Manager',9000,28,0,10,12,2800,'Territory Expansion: colonization range increased by 1 sector','Province Administrators oversee the full governance apparatus of a planetary territory. They manage budgets in the billions, coordinate military garrisons, and negotiate directly with the Senate on behalf of their province.'),
(71,'GOV-011','government','D','II','Legislature','Senate Representative',4,11,'SEN','Provincial Senator','Imperial Senate Representative','Tier 4 – Senator | Class D-II Senate Representative',12000,32,0,8,14,3500,'Senate Vote: +10% diplomatic bonus per active senator','Provincial Senators represent millions of constituents in the imperial legislative body. Their votes shape laws governing taxation, military conscription, and colonial expansion that affect the entire empire.'),
(72,'GOV-012','government','D','III','Executive','Territory Executive',4,12,'PGOV','Provincial Governor','Provincial Governor-General','Tier 4 – Provincial Governor | Class D-III Territory Executive',15000,36,0,12,15,4200,'Governor\'s Decree: issue one free policy change per turn','Provincial Governors-General hold near-absolute authority over planetary territories. They command local military garrisons, control treasury allocations, and can declare martial law in response to internal threats.'),
(73,'GOV-013','government','E','I','Executive','Security Minister',5,13,'MOD','Minister of Defense','Minister of Imperial Defense','Tier 5 – Def Minister | Class E-I Security Minister',25000,48,0,15,18,7000,'War Authorization: unlocks emergency military draft option','Ministers of Defense control the full military apparatus of the empire. They authorize offensive operations, set military budgets, and coordinate between the Supreme Commander and the political leadership.'),
(74,'GOV-014','government','E','II','Executive','Finance Minister',5,14,'MOE','Minister of Economy','Minister of Imperial Economy','Tier 5 – Econ Minister | Class E-II Finance Minister',30000,55,0,8,15,10000,'Economic Policy: empire-wide income +8%','Ministers of Economy govern the financial system of the entire empire. They manage currency supply, set interest rates, negotiate interstellar trade compacts, and ensure the economy can sustain both peacetime growth and wartime mobilization.'),
(75,'GOV-015','government','E','III','Executive','Head of Government',5,15,'PM','Prime Minister','Prime Minister of the Empire','Tier 5 – Prime Minister | Class E-III Head of Government',45000,65,0,18,20,15000,'Executive Command: issue two policy orders per turn','Prime Ministers lead the entire civilian government apparatus of the empire. They coordinate cabinet ministers, manage parliamentary coalitions, and translate imperial strategy into legislation and executive orders.'),
(76,'GOV-016','government','F','I','Imperial','Chief Imperial Advisor',6,16,'GV','Grand Vizier','Grand Vizier of the Empire','Tier 6 – Grand Vizier | Class F-I Chief Imperial Advisor',80000,90,0,20,28,25000,'Vizier\'s Counsel: reduces all policy costs by 15%','Grand Viziers serve as the supreme advisors to the Emperor, managing the intricate political networks that hold the empire together. Their counsel has shaped the outcomes of wars, alliances, and dynasties across centuries of recorded history.'),
(77,'GOV-017','government','F','II','Imperial','Administrative Head',6,17,'CHAN','Imperial Chancellor','Chancellor of the Imperial Order','Tier 6 – Imperial Chancellor | Class F-II Administrative Head',110000,105,0,22,25,32000,'Imperial Decree: bypass Senate vote for one action per turn','Imperial Chancellors administer the full bureaucratic machinery of the empire — millions of civil servants, dozens of ministries, and hundreds of administrative programs. They are the operational head of imperial governance.'),
(78,'GOV-018','government','F','III','Imperial','Imperial Guardian',6,18,'LP','Lord Protector','Lord Protector of the Realm','Tier 6 – Lord Protector | Class F-III Imperial Guardian',140000,120,30,45,30,38000,'Realm Protection: all defensive structures +20% effectiveness','Lord Protectors are empowered with both military and political authority to defend the empire against all internal and external threats. They command the Imperial Guard, oversee intelligence services, and have arrest authority over any citizen or official.'),
(79,'GOV-019','government','G','I','Intelligence','Data Operative',7,19,'IA','Intelligence Analyst','Imperial Intelligence Analyst','Tier 7 – Intel Analyst | Class G-I Data Operative',200000,140,0,10,80,20000,'Signal Intelligence: enemy covert actions detected +20%','Intelligence Analysts process, correlate, and synthesize information from surveillance networks, intercepted communications, and field operatives. Their assessments directly improve the empire\'s ability to anticipate and counter enemy operations.'),
(80,'GOV-020','government','G','II','Intelligence','Shadow Bureau Chief',7,20,'CDIR','Covert Director','Director of Imperial Covert Operations','Tier 7 – Covert Director | Class G-II Shadow Bureau Chief',300000,160,10,15,120,28000,'Shadow Network: covert operations cost 25% less','Covert Directors command the empire\'s clandestine services — networks of spies, saboteurs, and information brokers operating deep within enemy territories. They authorize black operations that states can never officially acknowledge.'),
(81,'GOV-021','government','G','III','Intelligence','Ghost Protocol Lead',7,21,'BOPS','Black Ops Coordinator','Imperial Black Operations Coordinator','Tier 7 – Black Ops | Class G-III Ghost Protocol Lead',450000,180,20,20,160,32000,'Ghost Fleet: all spy missions gain +30% success rate','Black Ops Coordinators plan and execute the most sensitive, deniable operations in the imperial playbook. They recruit, train, and deploy assets capable of destabilizing entire governments without a single confirmed action ever being traced back to the empire.'),
(82,'GOV-022','government','H','I','Sacred Order','Doctrine Enforcer',8,22,'PRI','Prior','Prior of the Sacred Order','Tier 8 – Prior | Class H-I Doctrine Enforcer',600000,200,40,30,50,40000,'Doctrine Suppression: target empire morale -10% for 4 turns','Priors serve as the field enforcers of sacred order doctrine. They arrive on worlds ahead of conquest fleets, converting populations through a combination of miracles, fear, and absolute authority backed by unstoppable force.'),
(83,'GOV-023','government','H','II','Sacred Order','Sacred Commander',8,23,'HP','High Prior','High Prior of the Sanctum','Tier 8 – High Prior | Class H-II Sacred Commander',900000,230,60,45,70,55000,'Holy War: +20% attack when declared against non-believers','High Priors command the sacred order\'s military doctrine on a regional scale. They coordinate Ori warrior deployments, manage Prior conversion networks, and serve as the supreme religious authority below the Doci.'),
(84,'GOV-024','government','H','III','Sacred Order','Supreme Prior',8,24,'DOC','Doci','Doci — Voice of the Ori','Tier 8 – Doci | Class H-III Supreme Prior',1400000,260,80,65,90,70000,'Voice of the Gods: all Ori-aligned units gain +25% power','The Doci is the supreme mortal representative of Ori divine will in the physical plane. As the Voice of the Ori, the Doci\'s commands carry the weight of divine law and their presence on a battlefield inspires absolute devotion in Ori forces while paralyzing those who stand against them.'),
(85,'GOV-025','government','I','I','Supreme','Planetary Ruler',9,25,'HS','High Sovereign','High Sovereign of the Realm','Tier 9 – High Sovereign | Class I-I Planetary Ruler',2500000,320,60,80,60,90000,'Sovereign Command: overrides all other empire orders for 1 turn','High Sovereigns hold absolute authority over entire planetary systems. Their rule is backed by military force, divine mandate, or democratic mandate — but in all cases their word is final and unquestionable within their domain.'),
(86,'GOV-026','government','I','II','Supreme','Sector Emperor',9,26,'EMP','Grand Emperor','Grand Emperor of the Sector','Tier 9 – Grand Emperor | Class I-II Sector Emperor',4500000,400,80,100,80,130000,'Imperial Edict: +15% all empire-wide production for 2 turns','Grand Emperors rule entire star sectors — dozens of inhabited systems and billions of subjects. Their courts maintain the administrative, military, and cultural apparatus of galactic-scale civilization.'),
(87,'GOV-027','government','I','III','Supreme','Galaxy Chancellor',9,27,'SC2','Supreme Chancellor','Supreme Chancellor of the Galaxy','Tier 9 – Supreme Chancellor | Class I-III Galaxy Chancellor',7000000,480,100,120,100,180000,'Galactic Mandate: all enemies suffer -5% power for 5 turns','Supreme Chancellors govern at the galactic scale, presiding over hundreds of star systems, thousands of inhabited worlds, and trillions of subjects. Their administrative challenge is comparable to managing a small universe.'),
(88,'GOV-028','government','J','I','Legendary','Knowledge Keeper',10,28,'AE','Ancient Elder','Ancient Elder of the Circle','Tier 10 – Ancient Elder | Class J-I Knowledge Keeper',12000000,600,0,100,200,300000,'Ascended Wisdom: research tree fully visible, all costs -25%','Ancient Elders are partially or fully ascended beings who have chosen to remain engaged with the physical universe. Their guidance to mortal governments introduces technologies and governance frameworks that would otherwise take civilizations centuries to develop independently.'),
(89,'GOV-029','government','J','II','Legendary','Intergalactic Ambassador',10,29,'AD','Ascended Diplomat','Ascended Diplomatic Envoy Eternal','Tier 10 – Ascended Diplomat | Class J-II Intergalactic Ambassador',20000000,700,0,80,250,450000,'Peace Mandate: no other empire can declare war for 3 turns','Ascended Diplomats operate across multiple planes of existence simultaneously, maintaining relationships with both physical and non-corporeal civilizations. Their interventions have ended wars that spanned entire galaxies and prevented apocalyptic conflicts between ancient races.'),
(90,'GOV-030','government','J','III','Legendary','Immortal Ruler',10,30,'ES','Eternal Sovereign','Eternal Sovereign of All Creation','Tier 10 – Eternal Sovereign | Class J-III Immortal Ruler',35000000,1000,200,300,300,1000000,'Eternal Dominion: no territory can be lost while active. All stats +20%','The Eternal Sovereign has transcended mortality entirely while retaining dominion over physical governance. They exist simultaneously in ascended form and as a physical ruler, possessing complete awareness of every corner of their empire and the ability to impose their will across all planes of existence simultaneously.');
/*!40000 ALTER TABLE `unit_catalog` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2026-08-01 22:53:24
